AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Application for importing purchase invoices
  
# Metadata to use for the publishing to the SAR
Metadata:
  AWS::ServerlessRepo::Application:
    Name: thetis-ims-purchase-invoice-import
    Description: Application for importing purchase invoices
    Author: thetis-apps
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.txt
    ReadmeUrl: README.md
    Labels: ['thetis-ims']
    HomePageUrl: https://github.com/thetis-apps/PurchaseInvoiceImport
    SemanticVersion: 2.0.23
    SourceCodeUrl: https://github.com/thetis-apps/PurchaseInvoiceImport

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs18.x
    MemorySize: 512

# Parameters of the application 
Parameters:
  ContextId:
    Type: String
    Description: Context that this application is handling events for.
    MinLength: '1'
  ClientId:
    Description: Key of the parameter that has your Thetis client id as its value.
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientId 
  ClientSecret:
    Description: Key of the parameter that has your Thetis client secret as its value.
    Type: AWS::SSM::Parameter::Value<String>
    Default: ThetisClientSecret
  ApiKey:
    Description: The api key that gives access to the context in Thetis IMS.
    Type: String
    MinLength: 1
  DevOpsEmail:
    Description: The email address to send mail to when messages in the dead letter queue.
    Type: String

Resources:

  CompletionTopic:
    Type: AWS::SNS::Topic
    Properties:
      KmsMasterKeyId: alias/aws/sns

  CompletionTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref CompletionTopic
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: textract.amazonaws.com
            Action: "SNS:Publish"
            Resource: "*"

  TextractRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: textract.amazonaws.com
            Action: sts:AssumeRole
      Description: Role for Textract to use when doing analysis.
      Policies:
        - PolicyName: TextractSNSPublishAndS3Read
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: !Ref CompletionTopic
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: "arn:aws:s3:::thetis-ims-test/*"

  # Initial Rule for fileAttached event
  Rule:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
        - public.thetis-ims.com
        detail-type:
        - fileAttached
        detail:
          entityName:
          - Supplier
          contextId:
          - Ref: ContextId
          attachmentType:
          - PURCHASE_INVOICE
      Targets:
      - Id: EventTarget
        Arn:
          Fn::GetAtt:
          - StartAnalysisFunction
          - Arn

  # Permission for EventBridge to invoke Lambda
  StartAnalysisPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
        - StartAnalysisFunction
        - Arn
      Principal: events.amazonaws.com

  # Lambda function that starts the analysis process
  StartAnalysisFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: built/handler.startAnalysisHandler
      MemorySize: 2048
      Timeout: 30
      Policies:
      - AmazonTextractFullAccess
      - AmazonS3FullAccess
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
          CompletionTopic:
            Ref: CompletionTopic
          TextractRole:
            !GetAtt TextractRole.Arn

  # Lambda function that processes the analysis results
  ProcessResultsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: built/handler.processResultsHandler
      MemorySize: 2048
      Timeout: 30
      Policies:
      - AmazonTextractFullAccess
      - AmazonS3FullAccess
      DeadLetterQueue:
        Type: SQS
        TargetArn:
          Fn::GetAtt:
          - DeadLetterQueue
          - Arn
      Environment:
        Variables:
          ClientId:
            Ref: ClientId
          ClientSecret:
            Ref: ClientSecret
          ApiKey:
            Ref: ApiKey
      Events:
        TextractCompletion:
          Type: SNS
          Properties:
            Topic: !Ref CompletionTopic

  # Dead letter queue for failed executions
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties: 
      KmsMasterKeyId: alias/aws/sqs

  # Alarm for DLQ
  DeadLetterQueueAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Alarm for messages in the DLQ
      Namespace: AWS/SQS
      MetricName: ApproximateNumberOfMessagesVisible
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DeadLetterQueue.QueueName
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 0
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref DeadLetterQueueTopic

  # SNS Topic for DLQ alerts
  DeadLetterQueueTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
        - Protocol: email
          Endpoint: !Ref DevOpsEmail